

ENV = 'development'

VUE_APP_BASE_API = '/hd/teacherTraining/api'
#返回空间地址
VUE_APP_RETURN_URL = 'https://basic.sc.smartedu.cn/hd/teacherTraining/home'
# title
  VUE_APP_ALL_TITLE = '四川智慧教育平台教师专题培训'
  VUE_APP_IS_PROD = '1'
#预览地址
VUE_APP_VIEW_URL = 'http://10.1.1.21:1080/ste/'
# 是否需要省级 0否1是
VUE_APP_ALL_PROVINCE = '0'
# 是否为市州级 0市1州
VUE_APP_ALL_CITY = '1'
# 是否需要证书模板自定义 0否1是
VUE_APP_IS_TEMPLATE = '0'
# 是否开启拥有外部资源 false 不开启 true 开启
VUE_APP_IS_OUTSIDE = true
